import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

import ResponsiveAppBar from "./components/ResponsiveAppBar";
import Footer from "./components/Footer";
import FloatingButtons from "./components/FloatingButtons";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ResponsiveAppBar />
          {/* {children} */}
          {/* <Footer /> */}
          {/* <FloatingButtons /> */}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
